module.exports = {
    OK: 'OK',
    BAD_REQUEST: 'wrong email or password',
    CONFLICT: 'conflict',
    NOT_FOUND: 'not found',
    UPDATED: 'successfully updated',
    SUCCESS: 'welcome!',
    UNAUTHORIZED: 'not authorized',
    WRONG_TEMPLATE: 'wrong template name',
    WRONG_TOKEN_TYPE: 'wrong token type',
    NO_TOKEN: 'no token',
    NO_CORS: 'CORS is not allowed',
    NOT_SUPPORTED_FORMAT: 'Not supported format',
    BIG_FILE: (name) => `File ${name} is too big`,
};
